[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
firstprogram = "Chn6UPzLDWASs7oLn3mvcpYREEHU5VZBjhX7zXAyyFFz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/joker/.config/solana/id.json"

[scripts]
test = "node tests/firstprogram.js"
